### ISSUE TITLE
Log API - incorrect parameters shown for info etc.

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#240]
Unclear if this is a bug or a documentation issue.

> Parameters
> message : STRING
> Log message.
> category : STRING Default: APP
> Log category.

Category seems to be required:

> I 08/08/2014 19:28:30:284 b056d000                  APP| App error: Wrong number of arguments: 1 instead of 2
>  apps/app/Settings/controller.rb:395:in 'info'
> apps/app/Settings/controller.rb:395:in 'block in set_log_preferences'

Line 395:

``` ruby
  Rho::Log.info msg
```

**Comment by michaelToews** [comment]
@rognar Cab you please tell me what the actual default for the Log API methods' categories are? The defaults reported in the XML seem to be wrong.

**Comment by alex-epifanoff** [comment]
@michaelToews @rognar default category should be "APP" but it seems that call to logging methods will fail if category is omitted. Seems like a bug.
