### ISSUE TITLE
Docs server fails on OSX

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhomobile-docs#316]
Is there a specific Ruby version requirement to run the docs server? Any other hints on getting it to run when installing from the rhomobile-docs repo? (As opposed to with RhoMobile Suite.)

No joy on OSX with Ruby 2.2.3:

☺ ➜  rhomobile-rhomobile-docs rvm gemset use rhomobile-docs                                               git:(master)
Using ruby-2.2.3 with gemset rhomobile-docs
☺ ➜  rhomobile-rhomobile-docs rvm gemset list                                                             git:(master)

gemsets for ruby-2.2.3 (found in /Users/jon/.rvm/gems/ruby-2.2.3)
   (default)
   global
=> rhomobile-docs
   watusi-rhodes-5.2.2-75fd4c2

☺ ➜  rhomobile-rhomobile-docs bundle install                                                              git:(master)
Fetching gem metadata from http://rubygems.org/.......
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Installing rake 0.9.2.2
Installing addressable 2.3.6
Installing nokogiri 1.5.10 with native extensions
Installing robotex 1.0.0
Installing anemone 0.7.2
Installing coderay 0.9.8
Installing colorize 0.5.8
Installing excon 0.43.0
Installing multipart-post 2.0.0
Installing faraday 0.9.1
Installing faraday_middleware 0.9.1
Installing multi_json 1.8.4
Installing heroku-api 0.3.17
Installing launchy 2.4.3
Installing netrc 0.7.9
Installing mime-types 1.25.1
Using rdoc 4.2.0
Installing rest-client 1.6.8
Installing rubyzip 1.1.6
Installing heroku 3.9.4
Installing yajl-ruby 1.2.1 with native extensions
Installing indextank 1.0.13
Installing json 1.8.2 with native extensions
Installing trollop 2.1.1
Installing link-checker 0.7.2
Installing pdfkit 0.6.2
Installing rack 1.3.10
Installing rack-codehighlighter 0.5.0
Installing rack-protection 1.5.3
Installing rack-rewrite 1.2.1
Installing rdiscount 1.6.8 with native extensions
Installing shotgun 0.9
Installing tilt 1.4.1
Installing sinatra 1.3.3
Installing xml-simple 1.1.4
Using bundler 1.10.6
Bundle complete! 16 Gemfile dependencies, 36 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from heroku:
 !    The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt.
 !    Download and install from: https://toolbelt.heroku.com
 !    For API access, see: https://github.com/heroku/heroku.rb
☺ ➜  rhomobile-rhomobile-docs rake start                                                                  git:(master)
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 0.9.2.2. Prepending `bundle exec` to your command may solve this.
/Users/jon/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup'
/Users/jon/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
/Users/jon/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
/Users/jon/workspace/rhomobile-rhomobile-docs/Rakefile:11:in `<top (required)>'
(See full trace by running task with --trace)
☹ ➜  rhomobile-rhomobile-docs gem list                                                                    git:(master)

*** LOCAL GEMS ***

addressable (2.3.6)
anemone (0.7.2)
bigdecimal (1.2.7, 1.2.6)
bundler (1.10.6)
bundler-unload (1.0.2)
coderay (0.9.8)
colorize (0.5.8)
excon (0.43.0)
executable-hooks (1.3.2)
faraday (0.9.1)
faraday_middleware (0.9.1)
gem-wrappers (1.2.7)
heroku (3.9.4)
heroku-api (0.3.17)
indextank (1.0.13)
io-console (0.4.3)
json (1.8.3, 1.8.2, 1.8.1)
launchy (2.4.3)
link-checker (0.7.2)
mime-types (1.25.1)
multi_json (1.8.4)
multipart-post (2.0.0)
netrc (0.7.9)
nokogiri (1.5.10)
pdfkit (0.6.2)
psych (2.0.15, 2.0.8)
rack (1.3.10)
rack-codehighlighter (0.5.0)
rack-protection (1.5.3)
rack-rewrite (1.2.1)
rake (10.4.2, 0.9.2.2)
rdiscount (1.6.8)
rdoc (4.2.0)
rest-client (1.6.8)
robotex (1.0.0)
rubygems-bundler (1.4.4)
rubyzip (1.1.6)
rvm (1.11.3.9)
shotgun (0.9)
sinatra (1.3.3)
tilt (1.4.1)
trollop (2.1.1)
xml-simple (1.1.4)
yajl-ruby (1.2.1)
☺ ➜  rhomobile-rhomobile-docs bundle exec rake start                                                      git:(master)
rebuilding API docs
Processing Adapter.xml
Processing Application.xml
      appBundleFolder no platform indicators
      appName no platform indicators
      appsBundleFolder no platform indicators
      bundleFolder no platform indicators
      configPath no platform indicators
      country no platform indicators
      databaseBlobFolder no platform indicators
      locale no platform indicators
      modelsManifestPath no platform indicators
      publicFolder no platform indicators
      settingsPageURI no platform indicators
      splash no platform indicators
      startURI no platform indicators
      userFolder no platform indicators
      version no platform indicators
      databaseFilePath no platform indicators
      expandDatabaseBlobFilePath no platform indicators
      modelFolderPath no platform indicators
      quit no platform indicators
      relativeDatabaseBlobFilePath no platform indicators
Processing audiocapture.xml
Processing barcode.xml
      getSupportedProperties no platform indicators
Processing battery.xml
Processing btdiscover.xml
      enumerate no platform indicators
Processing camera.xml
      choosePicture no platform indicators
Processing cardreader.xml
Processing Config.xml
      configPath no platform indicators
      getPropertyBool no platform indicators
      getPropertyInt no platform indicators
      getPropertyString no platform indicators
      isPropertyExists no platform indicators
      loadFromFile no platform indicators
      removeProperty no platform indicators
      setPropertyBool no platform indicators
      setPropertyInt no platform indicators
      setPropertyString no platform indicators
Processing Configreadwrite.xml
Processing ConnectionChecking.xml
      hostURL no platform indicators
      message no platform indicators
      pollInterval no platform indicators
      timeout no platform indicators
      trackConnection no platform indicators
Processing Database.xml
      close no platform indicators
      commitTransaction no platform indicators
      destroyTable no platform indicators
      destroyTables no platform indicators
      executeBatchSql no platform indicators
      executeSql no platform indicators
      initialize no platform indicators
      isTableExist no platform indicators
      rollbackTransaction no platform indicators
      startTransaction no platform indicators
Processing device.xml
Processing deviceMemory.xml
Processing eventsource.xml
      onerror no platform indicators
      onmessage no platform indicators
      onopen no platform indicators
      readyState no platform indicators
      url no platform indicators
      withCredentials no platform indicators
      addEventListener no platform indicators
      close no platform indicators
Processing File.xml
      basename no platform indicators
      close no platform indicators
      copy no platform indicators
      deleteDir no platform indicators
      deleteFile no platform indicators
      deleteRecursive no platform indicators
      dirname no platform indicators
      exists no platform indicators
      flush no platform indicators
      getFileSize no platform indicators
      isDir no platform indicators
      isFile no platform indicators
      isOpened no platform indicators
      join no platform indicators
      listDir no platform indicators
      makeDir no platform indicators
      makeDirs no platform indicators
      open no platform indicators
      read no platform indicators
      read no platform indicators
      readAll no platform indicators
      rename no platform indicators
      seek no platform indicators
      size no platform indicators
      write no platform indicators
Processing Intent.xml
      send no platform indicators
      startListening no platform indicators
      stopListening no platform indicators
Processing keycapture.xml
Processing keystate.xml
Processing Log.xml
      destination no platform indicators
      destinationURI no platform indicators
      excludeCategories no platform indicators
      excludeFilter no platform indicators
      filePath no platform indicators
      fileSize no platform indicators
      includeCategories no platform indicators
      level no platform indicators
      skipPost no platform indicators
      cleanLogFile no platform indicators
      error no platform indicators
      fatalError no platform indicators
      info no platform indicators
      readLogFile no platform indicators
      sendLogFile no platform indicators
      trace no platform indicators
      warning no platform indicators
Processing logcapture.xml
      excludeCategories no platform indicators
      maxLines no platform indicators
      clear no platform indicators
      numLines no platform indicators
      read no platform indicators
      start no platform indicators
      stop no platform indicators
Processing mediaplayer.xml
      startvideo no platform indicators
Processing Message.xml
Processing MobilePayment.xml
      abort no platform indicators
      authorizeCard no platform indicators
      close no platform indicators
      completeOnlineEmv no platform indicators
      createMac no platform indicators
      getBatteryLevel no platform indicators
      getDeviceInfo no platform indicators
      getEmvTags no platform indicators
      getLowBatteryThreshold no platform indicators
      isOpened no platform indicators
      open no platform indicators
      promptAdditionalInfo no platform indicators
      promptMenu no platform indicators
      promptMessage no platform indicators
      promptPin no platform indicators
      readCardData no platform indicators
      removeCard no platform indicators
      setEmvTags no platform indicators
      setLowBatteryThreshold no platform indicators
      validateMac no platform indicators
Processing NativeMenubar.xml
Processing NativeTabbar.xml
      create no platform indicators
      currentTabIndex no platform indicators
      remove no platform indicators
      switchTab no platform indicators
Processing NativeToolbar.xml
      create no platform indicators
      remove no platform indicators
Processing Navbar.xml
Processing Network.xml
      authPassword no platform indicators
      authType no platform indicators
      authUser no platform indicators
      headers no platform indicators
      httpVerb no platform indicators
      responseTimeout no platform indicators
      url no platform indicators
      cancel no platform indicators
      detectConnection no platform indicators
      downloadFile no platform indicators
      get no platform indicators
      post no platform indicators
      stopDetectingConnection no platform indicators
      uploadFile no platform indicators
Processing NewORM.xml
      databaseClientReset no platform indicators
      databaseFullReset no platform indicators
      databaseFullResetAndLogout no platform indicators
      databaseFullResetEx no platform indicators
      databaseFullclientResetAndLogout no platform indicators
      databaseLocalReset no platform indicators
      generateId no platform indicators
      getClientId no platform indicators
      haveLocalChanges no platform indicators
      useNewOrm no platform indicators
Processing NewORMModel.xml
      associations no platform indicators
      fixed_schema no platform indicators
      freezed no platform indicators
      loaded no platform indicators
      model_name no platform indicators
      partition no platform indicators
      source_id no platform indicators
      sync_priority no platform indicators
      sync_type no platform indicators
      anyChangedObjects no platform indicators
      buildComplexWhereCond no platform indicators
      buildFindLimits no platform indicators
      buildFindOrder no platform indicators
      buildSimpleWhereCond no platform indicators
      canModify no platform indicators
      clear no platform indicators
      createInstance no platform indicators
      createObject no platform indicators
      deleteObject no platform indicators
      deleteObjects no platform indicators
      deleteObjectsPropertyBagByCondArray no platform indicators
      deleteObjectsPropertyBagByCondHash no platform indicators
      destroy no platform indicators
      enable no platform indicators
      enumerate no platform indicators
      findObjects no platform indicators
      findObjectsPropertyBagByCondArray no platform indicators
      findObjectsPropertyBagByCondHash no platform indicators
      find_by_sql no platform indicators
      getBackendRefreshTime no platform indicators
      getBelongsTo no platform indicators
      getCount no platform indicators
      getModel no platform indicators
      getModelProperty no platform indicators
      hasChanges no platform indicators
      init no platform indicators
      initModel no platform indicators
      onSyncCreateError no platform indicators
      onSyncDeleteError no platform indicators
      onSyncUpdateError no platform indicators
      pushChanges no platform indicators
      saveObject no platform indicators
      set no platform indicators
      setBelongsTo no platform indicators
      setModelProperty no platform indicators
      setSchemaIndex no platform indicators
      updateObject no platform indicators
      validateFreezedAttribute no platform indicators
      validateFreezedAttributes no platform indicators
Processing Notification.xml
Processing Orm.xml
      addModel no platform indicators
      databaseFullReset no platform indicators
      databaseFullResetAndLogout no platform indicators
      databaseFullResetEx no platform indicators
      databaseFullclientResetAndLogout no platform indicators
      databaseLocalReset no platform indicators
      export no platform indicators
      getClientId no platform indicators
      getModel no platform indicators
      haveLocalChanges no platform indicators
      import no platform indicators
Processing OrmModel.xml
      canModify no platform indicators
      create no platform indicators
      deleteAll no platform indicators
      destroy no platform indicators
      find no platform indicators
      get no platform indicators
      has no platform indicators
      make no platform indicators
      object no platform indicators
      save no platform indicators
      set no platform indicators
      updateAttributes no platform indicators
      vars no platform indicators
Processing printing.xml
docs/en/edge/api/printing.xmltrying to use singleton
Processing printingepson.xml
      simpleStringProperty no platform indicators
      calcSumm no platform indicators
      enumerate no platform indicators
      getPlatformName no platform indicators
      joinStrings no platform indicators
Processing printingzebra.xml
Has a template
{"path"=>"../../printing/ext/printing.xml"}
{"DESC"=>["General properties for Printer."], "PROPERTY"=>[{"name"=>"ID", "type"=>"STRING", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Unique printer ID during application lifetime."]}, {"name"=>"deviceName", "type"=>"STRING", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Bluetooth/Network name of printer."]}, {"name"=>"printerType", "type"=>"STRING", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Type of printer - see PRINTER_TYPE_... constants."]}, {"name"=>"deviceAddress", "type"=>"STRING", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["IP address for TCP (wireless) connection. Bluetooth(R) mac or device serial number. Note: iOS uses device serial number instead of mac address. If you need to get device mac you can use CPCL command ! U1 getvar \"bluetooth.address\" "], "DESC_EB"=>["IP address for TCP (wireless) connection. Bluetooth(R) mac or device serial number. If you need to get device mac you can use CPCL command ! U1 getvar \"bluetooth.address\" "]}, {"name"=>"devicePort", "type"=>"INTEGER", "generateAccessors"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Default port when connecting using TCP/IP."]}, {"name"=>"connectionType", "type"=>"STRING", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Type of connection to printer."]}, {"name"=>"isConnected", "type"=>"BOOLEAN", "readOnly"=>"true", "VER_INTRODUCED"=>["4.1.0"], "PLATFORM"=>["WM, CE, Android, iOS"], "PLATFORM_EB"=>["WM, CE, Android"], "DESC"=>["Connection status flag. All other properties are valid only if isConnect equals to true. Please keep in mind: this property do not guarantee real connection, because all real device functionality processed in separated thread asynchronously. If you want to real physical connection - use requestState() method with receive result in the callback. Only this way process real request to device and analyze answer from device."]}]}
docs/en/edge/api/printingzebra.xmltrying to use singleton
Processing process.xml
      closeHandle no platform indicators
      getProcessExitCode no platform indicators
      runApplication no platform indicators
      waitForApplication no platform indicators
Processing push.xml
      pushAppName no platform indicators
      pushServer no platform indicators
      type no platform indicators
      enumerate no platform indicators
      getDeviceId no platform indicators
      startNotifications no platform indicators
      stopNotifications no platform indicators
Processing Record.xml
Processing RhoConnectClient.xml
      bulksyncState no platform indicators
      pageSize no platform indicators
      pollInterval no platform indicators
      showStatusPopup no platform indicators
      sslVerifyPeer no platform indicators
      syncServer no platform indicators
      userName no platform indicators
      addObjectNotify no platform indicators
      cleanObjectNotify no platform indicators
      clearNotification no platform indicators
      doSync no platform indicators
      doSyncSource no platform indicators
      isLoggedIn no platform indicators
      isSyncing no platform indicators
      login no platform indicators
      logout no platform indicators
      search no platform indicators
      setNotification no platform indicators
      setObjectNotification no platform indicators
      stopSync no platform indicators
Processing screenorientation.xml
Processing sensor.xml
docs/en/edge/api/sensor.xmltrying to use singleton
      minimumGap no platform indicators
      status no platform indicators
      type no platform indicators
Processing signalindicators.xml
Processing signature.xml
Processing SimulScan.xml
Processing smartcradle.xml
      cApiVersion no platform indicators
      chargeState no platform indicators
      columnId no platform indicators
      driverVersion no platform indicators
      firmwareVersion no platform indicators
      hardwareId no platform indicators
      mfgDate no platform indicators
      partNumber no platform indicators
      rowId no platform indicators
      serialNumber no platform indicators
      wallId no platform indicators
Processing system.xml
      country no platform indicators
      deviceName no platform indicators
      devicePushId no platform indicators
      freeServerPort no platform indicators
      hasCalendar no platform indicators
      hasCamera no platform indicators
      hasCellNetwork no platform indicators
      hasNetwork no platform indicators
      hasSqlite no platform indicators
      hasTouchscreen no platform indicators
      hasWifiNetwork no platform indicators
      isEmulator no platform indicators
      isMotorolaDevice no platform indicators
      isRhoSimulator no platform indicators
      isSymbolDevice no platform indicators
      localServerPort no platform indicators
      locale no platform indicators
      osVersion no platform indicators
      platform no platform indicators
      ppiX no platform indicators
      ppiY no platform indicators
      realScreenHeight no platform indicators
      realScreenWidth no platform indicators
      screenHeight no platform indicators
      screenOrientation no platform indicators
      screenWidth no platform indicators
      webviewFramework no platform indicators
      clearNetworkStatusNotify no platform indicators
      deleteFolder no platform indicators
      exit no platform indicators
      get_locale no platform indicators
      isBlobAttr no platform indicators
      openUrl no platform indicators
      setNetworkStatusNotify no platform indicators
      setPushNotification no platform indicators
      set_locale no platform indicators
      set_sleeping no platform indicators
      startTimer no platform indicators
      stopTimer no platform indicators
      unzipFile no platform indicators
      updateBlobAttribs no platform indicators
      zipFile no platform indicators
      zipFiles no platform indicators
Processing Tag.xml
Processing Timer.xml
      create no platform indicators
      isAlive no platform indicators
      start no platform indicators
      stop no platform indicators
Processing videocapture.xml
      enumerate no platform indicators
Processing websocket.xml
      onclose no platform indicators
      onerror no platform indicators
      onmessage no platform indicators
      onopen no platform indicators
      readyState no platform indicators
      url no platform indicators
Processing webview.xml
      activeTab no platform indicators
      framework no platform indicators
      active_tab no platform indicators
      currentLocation no platform indicators
      executeJavascript no platform indicators
      full_screen_mode no platform indicators
      navigate no platform indicators
      navigateBack no platform indicators
      refresh no platform indicators
== Shotgun/WEBrick on http://127.0.0.1:9393/
[2015-10-16 11:10:22] INFO  WEBrick 1.3.1
[2015-10-16 11:10:22] INFO  ruby 2.2.3 (2015-08-18) [x86_64-darwin14]
[2015-10-16 11:10:22] INFO  WEBrick::HTTPServer#start: pid=81299 port=9393
URI::InvalidURIError - bad URI(is not URI?): :
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/uri/rfc3986_parser.rb:17:in `rescue in split'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/uri/rfc3986_parser.rb:14:in `split'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/indextank-1.0.13/lib/indextank.rb:16:in `setup_connection'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/indextank-1.0.13/lib/indextank/client.rb:10:in `initialize'
	/Users/jon/workspace/rhomobile-rhomobile-docs/docs.rb:390:in `new'
	/Users/jon/workspace/rhomobile-rhomobile-docs/docs.rb:390:in `recent_updates'
	/Users/jon/workspace/rhomobile-rhomobile-docs/docs.rb:120:in `block (2 levels) in <class:Docs>'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:1265:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:1265:in `block in compile!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `block (3 levels) in route!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `block (2 levels) in route!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `block in process_route'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `block in route!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `block in call!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `block in invoke'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-codehighlighter-0.5.0/lib/rack/codehighlighter.rb:25:in `call'
	/Users/jon/workspace/rhomobile-rhomobile-docs/pdfmaker.rb:7:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/nulllogger.rb:9:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/head.rb:9:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-rewrite-1.2.1/lib/rack/rewrite.rb:20:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/lint.rb:48:in `_call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/lint.rb:36:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/showexceptions.rb:24:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/commonlogger.rb:20:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/shotgun-0.9/lib/shotgun/static.rb:14:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/builder.rb:134:in `call'
	/Users/jon/.rvm/gems/ruby-2.2.3@rhomobile-docs/gems/rack-1.3.10/lib/rack/handler/webrick.rb:59:in `service'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/jon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by thanizebra** [comment]
use ruby-2.1.7
